# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: dapr-dev-container

on:
  push:
    paths:
      - '.github/**'
      - 'docker/Dockerfile-dev'
  pull_request:
    paths:
      - '.github/**'
      - 'docker/Dockerfile-dev'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  build:
    name: build dev container
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: https://docker.pkg.github.com
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login https://docker.pkg.github.com -u tomkerkhove -p ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: build dapr-dev-container
        run: make build-dev-container DAPR_REGISTRY=${{ env.DOCKER_REGISTRY }}
      - name: push container
        run: make push-dev-container DAPR_REGISTRY=${{ env.DOCKER_REGISTRY }}